### ISSUE TITLE
Update README!

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [nishkarsh800/LeetCode-Contests#1]
Plz assign me

**Comment by nishkarsh800** [comment]
@Soumya-Kushwaha Kindly elaborate that how will you enhance the readme?

**Comment by Soumya-Kushwaha** [comment]
I will add contributors section and open source programs this repo has been a part of!

**Comment by Soumya-Kushwaha** [comment]
Also @nishkarsh800 kindly pin the repo link in discord channel. People will start contributing!
