### ISSUE TITLE
Add Biweekly Contest 79

### ISSUE THREAD

**Issue by Rakesh9100** [nishkarsh800/LeetCode-Contests#17]
### Title
Will add Biweekly Contest 79 solutions.

### Description
1. Check if Number Has Equal Digit Count and Digit Value
2. Sender With Largest Word Count
3. Maximum Total Importance of Roads
4. Booking Concert Tickets in Groups

#### Are you contributing under any open-source program ?
HSOC22
<hr/>

**Comment by nishkarsh800** [comment]
Add only one contest at a time

**Comment by Rakesh9100** [comment]
> Add only one contest at a time

Ohkk
