### ISSUE TITLE
Biweekly Contest 81

### ISSUE THREAD

**Issue by Rakesh9100** [nishkarsh800/LeetCode-Contests#18]
### Title
(Write issue title over here)
Will add Biweekly Contest 81 Solutions.
### Description
(Describe the issue over here)
1. Count Asterisks
2. Count Unreachable Pairs of Nodes in an Undirected Graph
3. Maximum XOR After Operations
4. Number of Distinct Roll Sequences

#### Are you contributing under any open-source program ?
HSOC22
<hr/>

**Comment by nishkarsh800** [comment]
@Rakesh9100 Make a pr for the previous issue only then this issue will be assigned.

**Comment by Rakesh9100** [comment]
> @Rakesh9100 Make a pr for the previous issue only then this issue will be assigned.

Kindlr review previous issue PR and assign this one. @nishkarsh800

**Comment by nishkarsh800** [comment]
@Rakesh9100 Firstly make your PR correctly and in a well structured manner. Then I would assign you this issue.
