### ISSUE TITLE
Biweekly Contest 83

### ISSUE THREAD

**Issue by Shweta2024** [nishkarsh800/LeetCode-Contests#2]
## Description
 Add code to the problems of Biweekly Contest 83. 
Below are the problems of the Biweekly83 :- 
- [Best Poker Hand](https://leetcode.com/contest/biweekly-contest-83/problems/best-poker-hand)
- [Number of Zero-Filled Subarrays](https://leetcode.com/contest/biweekly-contest-83/problems/number-of-zero-filled-subarrays)
- [Design a Number Container System](https://leetcode.com/contest/biweekly-contest-83/problems/design-a-number-container-system)
- [Shortest Impossible Sequence of Rolls](https://leetcode.com/contest/biweekly-contest-83/problems/shortest-impossible-sequence-of-rolls)

**Comment by Shweta2024** [comment]
@nishkarsh800 can you please assign me this issue?

**Comment by nishkarsh800** [comment]
@Shweta2024 Close the issue by today midnight .

**Comment by Shweta2024** [comment]
> @Shweta2024 Close the issue by today midnight .

Here is the link of the pr :- Add Biweekly83 #6 , please review it.
Thank you
