### ISSUE TITLE
Weekly Contest 306

### ISSUE THREAD

**Issue by coderSuren** [nishkarsh800/LeetCode-Contests#28]
### Title
Weekly Contest 306
### Description
I would like to add solutions for Weekly Contest [306](https://leetcode.com/contest/weekly-contest-306/).

Problems:
1. [Largest Local Values in a Matrix](https://leetcode.com/contest/weekly-contest-306/problems/largest-local-values-in-a-matrix)
2. [Node With Highest Edge Score](https://leetcode.com/contest/weekly-contest-306/problems/node-with-highest-edge-score)
3. [Construct Smallest Number From DI String](https://leetcode.com/contest/weekly-contest-306/problems/construct-smallest-number-from-di-string)
4. [Count Special Integers](https://leetcode.com/contest/weekly-contest-306/problems/count-special-integers)

#### Are you contributing under any open-source program ?
HSSOC' 22
<hr/>

**Comment by nishkarsh800** [comment]
Close the issue by tomorrow 12pm
