### ISSUE TITLE
Weekly Contest 298

### ISSUE THREAD

**Issue by Avik-creator** [nishkarsh800/LeetCode-Contests#4]
I want to add these questions from leetcode weekly Contest:

* Greatest English Letter in Upper and Lower Case
* Sum of Numbers With Units Digit K
* Longest Binary Subsequence Less Than or Equal to K
* Selling Pieces of Wood

**Comment by nishkarsh800** [comment]
@Avik-creator Read the contributing guidelines and then write what you wanna do in this issue briefly.

**Comment by Avik-creator** [comment]
@nishkarsh800 please check it

**Comment by nishkarsh800** [comment]
Yeah now it looks fine :)

**Comment by Avik-creator** [comment]
@nishkarsh800 I code in Java. Will that be ok?

**Comment by nishkarsh800** [comment]
@Avik-creator Read the contributing guidelines

**Comment by Avik-creator** [comment]
@nishkarsh800 i have read it sir.
