### ISSUE TITLE
Want to add Leetcode weekly 297

### ISSUE THREAD

**Issue by Avik-creator** [nishkarsh800/LeetCode-Contests#7]
**Problem list:**

* Calculate Amount Paid in Taxes	
* Minimum Path Cost in a Grid	
* Fair Distribution of Cookies	
* Naming a Company

**Comment by Avik-creator** [comment]
@nishkarsh800 please assign me this

**Comment by nishkarsh800** [comment]
@Avik-creator Unassigned since you haven't created a PR in the given amount of time.

**Comment by Avik-creator** [comment]
@nishkarsh800 i am having my college just give more 1 day

**Comment by nishkarsh800** [comment]
Complete the PR by today midnight. From the next time, be aware.

**Comment by Avik-creator** [comment]
@nishkarsh800 yes
